version: '3'

name: '2023-09-orleans-cda-projet2-dev'

services:
  api:
    build:
      dockerfile: ./deployment/DockerfileBackendApi
      context: ../
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./common.env
      - ./api.env
    environment:
      - NODE_ENV=production

  web:
    build:
      dockerfile: ./deployment/DockerfileFrontendWeb
      context: ../
    volumes:
      - web-client-build:/app
    env_file:
      - ./common.env
      - ./web.env
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:1.23.3
    depends_on:
      - web
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build

  database:
    image: mysql:8.2.0
    restart: always
    # ports:
    #   - ${MYSQL_PORT}:3306
    env_file:
      - ./.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uuser', '-ppassword']
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s

  migrations:
    build:
      dockerfile: ./deployment/DockerfileBackendMigrations
      context: ../
    depends_on:
      - database
    env_file:
      - ./common.env
      - ./api.env
    environment:
      - NODE_ENV=production

volumes:
  web-client-build:
