version: '3.3'

services:
  api:
    build:
      dockerfile: ./deployment/DockerfileBackendApi
      context: ../
    image: mikazian/tindev-backendapi-staging

  web:
    build:
      dockerfile: ./deployment/DockerfileFrontendWeb
      context: ../
    image: mikazian/tindev-frontendweb-staging

  migrations:
    build:
      dockerfile: ./deployment/DockerfileBackendMigrations
      context: ../
    image: mikazian/tindev-backendmigrations-staging
