name: '2023-09-orleans-cda-projet2-dev'

services:
  nginx:
    image: nginx:1.23.3
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf

  database:
    image: mysql:8.2.0
    restart: always
