version: '3'

name: '2023-09-orleans-cda-projet2-staging'

services:
  api:
    image: mikazian/tindev-backendapi-staging
    restart: always
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./common.env
      - ./api.env
    networks:
      - db
      - backend

  web:
    image: mikazian/tindev-frontendweb-staging
    volumes:
      - web-client-build:/app
    env_file:
      - ./common.env
      - ./web.env
    networks:
      - frontend

  nginx:
    image: nginx:1.23.3
    depends_on:
      - web
      - api
    restart: always
    ports:
      - ${GATEWAY_PORT}:8080
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
    networks:
      - backend
      - frontend

  database:
    image: mysql:8.2.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uuser', '-ppassword']
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s
    networks:
      - db

  migrations:
    image: mikazian/tindev-backendmigrations-staging
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./common.env
      - ./api.env
    networks:
      - db

volumes:
  web-client-build:

networks:
  backend:
  frontend:
  db:
